name: Infrastructure Deployment

on:
  push:
    branches:
      - main # Trigger when pushing to main branch
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        run: |
          echo "Setting AWS credentials..."
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" >> ~/.aws/credentials
          cat ~/.aws/credentials
      - name: Terraform Init
        run: terraform init -backend-config="bucket=infra-project-terraform-state-bucket"
        working-directory: terraform
      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: terraform
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: terraform apply -auto-approve
        working-directory: terraform
      - name: Update Inventory JSON
        run: |
          terraform output -json > $GITHUB_WORKSPACE/ansible/inventory.json
          cat $GITHUB_WORKSPACE/ansible/inventory.json
        working-directory: terraform

  ansible:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/trojan.pem
          chmod 600 ~/.ssh/trojan.pem
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/trojan.pem

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.py webserver.yml
        working-directory: ansible
